services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: contractiq-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: contractiq
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: contractiq
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: contractiq-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: contractiq
      MONGO_INITDB_ROOT_PASSWORD: devpassword
    volumes:
      - mongo_data:/data/db

  ollama:
    image: ollama/ollama:latest
    container_name: contractiq-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  maildev:
    image: maildev/maildev:latest
    container_name: contractiq-maildev
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  postgres_data:
  mongo_data:
  ollama_data:
