package com.contractiq.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.chat.model.ChatModel;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.ai.chat.prompt.Prompt;
import org.springframework.stereotype.Service;

@Service
public class ContractAiService {

    private static final Logger log = LoggerFactory.getLogger(ContractAiService.class);

    private final ChatModel chatModel;

    public ContractAiService(ChatModel chatModel) {
        this.chatModel = chatModel;
    }

    public String generateResponse(String promptText) {
        log.info("Generating AI response for prompt length: {}", promptText.length());
        try {
            ChatResponse chatResponse = chatModel.call(new Prompt(promptText));
            if (chatResponse != null && chatResponse.getResult() != null && chatResponse.getResult().getOutput() != null) {
                return chatResponse.getResult().getOutput().getContent();
            }
            return "No response generated by the local AI model.";
        } catch (Exception e) {
            log.error("Ollama AI connection failed. Ollama server might be offline on port 11434.", e);
            return "Error: Local Ollama service is unreachable. Please ensure Ollama is running locally with Llama 3 loaded.";
        }
    }
}
